name: adapt
description: A flutter plugin for adapting screen.Adapt IOS and Android.
version: 0.0.1
author: zane <752636052@qq.com>
homepage: https://github.com/wangweianger/adapt_flutter

environment:
    sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

dev_dependencies:
    flutter_test:
        sdk: flutter

